server:
  port: 7066

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console